### ISSUE TITLE
First element not showing avatar or styles

### ISSUE THREAD

**Issue by MrRa1n** [WhiteNeo/lastposter-avatar-mybb18x-series#2] opened 2015-09-29 18:11 UTC
I have installed an configured your plugin and it looks great!

The only trouble I am having is that the first element in the first forum is not showing user avatars and is also unstyled compared to the other forums.

Here is a screenshot: http://puu.sh/ksBaX/bb63370e0d.png

**Comment by WhiteNeo** [comment] 2015-09-30 06:27
Do you have forum url ?

It's strange, i have it on my forums and no errors.

http://soportemybb.es

**Comment by MrRa1n** [comment] 2015-09-30 11:43
I had fixed it temporarily by deleting the thread it was appearing on (Welcome to Pavili0n).

I have restored it in the meantime for you to have a look - https://pavili0n.com/

**Comment by WhiteNeo** [comment] 2015-10-02 23:25
Yes i see that error but i cannot reproduce it to fix it.

Did you have any idea on how to reproduce it ?

**Comment by WhiteNeo** [comment] 2016-03-01 04:27
Fixed on latest revision.

**Closed by WhiteNeo** 2016-03-01 04:27 UTC
